#!/bin/bash
set -e

rm -rf output
mkdir output

cp asm_samples/build asm_samples/link asm_samples/uwdo asm_samples/output output/
cp asm_samples/runtime.s output/

./joosc asm_samples/*.java

(
  cd output
  ./uwdo "./build && ./link && ./main && echo All done!"
)
