#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Please specifiy which test suite to run. For example, a1, a2.."
    exit 1
fi
ALL_FILES="extern/testcases/$1/*"

touch generated/completed_tests_$1

stdlib=`find extern/stdlib/2.0/ -iname *.java`

for file in $ALL_FILES; do
    grep $file generated/completed_tests_$1 >/dev/null
    SKIP=$?
    if [ $SKIP -eq 0 ]; then
      continue
    fi

    printf "Processing $file..."
    should_fail_check=${file##*/}
    should_fail_check=${should_fail_check%.java}
    grep $should_fail_check scripts/should_fail_$1
    EXC=$?

    if [[ -d $file ]]; then # if the file is a directory
        ./joosc $stdlib `find $file -type f`
    else
        ./joosc $stdlib $file
    fi
    JOOSC=$?

    if [ $EXC -eq 0 ]; then
        if [ $JOOSC -ne 42 ]; then
            printf "FAILED, expected 42\n"
            continue
        fi
    else
        if [ $JOOSC -ne 0 ]; then
            printf "FAILED, expected 0\n"
            continue
        fi
    fi
    printf "OK\n"
    echo $file >> generated/completed_tests_$1
done
