#!/bin/sh
ALL_FILES="extern/testcases/a1/*"

touch generated/completed_tests

for file in $ALL_FILES; do

    grep $file generated/completed_tests >/dev/null
    SKIP=$?
    if [ $SKIP -eq 0 ]; then
      continue
    fi

    printf "Processing $file..."
    head -n3 $file | grep 'EXCEPTION\|INVALID'
    EXC=$?

    ./joosc $file >/dev/null
    JOOSC=$?

    if [ $EXC -eq 0 ]; then
        if [ $JOOSC -ne 42 ]; then
            printf "FAILED, expected 42 but got 0\n"
            continue
        fi
    else
        if [ $JOOSC -ne 0 ]; then
            printf "FAILED, expected 0 but got 42\n"
            continue
        fi
    fi
    printf "OK\n"
    echo $file >> generated/completed_tests
done
