#!/usr/bin/python
from multiprocessing.pool import Pool

import sys
import os.path

from joos.errors import JoosError

from joos.joosc import (ScanInput,
                        PrepareTokens,
                        Parse,
                        BuildAST,
                        PrintAST,
                        WeedAST,
                        BuildEnv,
                        LinkTypes)


JOOS_CACHE = 'generated/joos.cache'
JOOS_LR1_FILE = 'generated/joos.lr1'


def ProcessFile(input_file):
    with open(input_file) as f:
        tokens = ScanInput(f.read())
        tokens = PrepareTokens(tokens, input_file)
        parse_tree = Parse(tokens, JOOS_LR1_FILE)
        ast = BuildAST(parse_tree)
        WeedAST(ast, input_file)
        BuildEnv(ast)
        return ast


def ProcessFiles(input_files):
    units = []
    for file in input_files:
        ast = ProcessFile(file)
        units.append(ProcessFile(file))
    return units


def MultiProcessFiles(input_files):
    pool = Pool(processes=4)
    units = pool.map(ProcessFile, input_files)
    return units


def Main(input_files):
    try:
        units = MultiProcessFiles(input_files)
        LinkTypes(units)
    except JoosError, e:
        print >> sys.stderr, str(e)
        sys.exit(42)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print "Usage: joosc [input_files...]"
    else:
        Main(sys.argv[1:])
